version: '3.9'

services:

  main:
    container_name: main
    image: projectnestjs
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 52827:8080

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "52826:80"

  swagger-ui:
    container_name: swagger_ui
    image: swaggerapi/swagger-ui
    ports:
      - "8070:8080"
    volumes:
      - ./doc:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/openapi.yaml
    restart: always

volumes:
  postgres: